-- MySQL Script generated by MySQL Workbench
-- Tue Jan  7 10:58:28 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tblRole`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tblRole` (
  `fldRole_Id` INT NOT NULL,
  `fldRoleName` VARCHAR(45) NULL,
  PRIMARY KEY (`fldRole_Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tblUser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tblUser` (
  `flduser_Id` INT NOT NULL,
  `fldName` VARCHAR(45) NULL,
  `fldEmail` VARCHAR(45) NULL,
  `fldPassword` VARCHAR(150) NOT NULL,
  `fldRoleId` INT NULL,
  PRIMARY KEY (`flduser_Id`),
  INDEX `fldRoleId_idx` (`fldRoleId` ASC) VISIBLE,
  CONSTRAINT `fldRoleId`
    FOREIGN KEY (`fldRoleId`)
    REFERENCES `mydb`.`tblRole` (`fldRole_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tblAddress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tblAddress` (
  `fldAddress_Id` INT NOT NULL,
  `fldUserId` INT NULL,
  `fldName` VARCHAR(45) NULL,
  `fldPincode` VARCHAR(45) NULL,
  `fldState` VARCHAR(45) NULL,
  `fldCity` VARCHAR(45) NULL,
  `fldArea` VARCHAR(45) NULL,
  `fldBuilding` VARCHAR(45) NULL,
  `fldPhoneNumber` VARCHAR(45) NULL,
  `fldActive` INT NULL,
  `fldUpdatedOn` DATETIME NULL,
  `fldDeletedOn` DATETIME NULL,
  `fldLocationType` VARCHAR(45) NULL,
  PRIMARY KEY (`fldAddress_Id`),
  INDEX `userid_idx` (`fldUserId` ASC) VISIBLE,
  CONSTRAINT `userid`
    FOREIGN KEY (`fldUserId`)
    REFERENCES `mydb`.`tblUser` (`flduser_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tblOrder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tblOrder` (
  `fldOrder_Id` INT NOT NULL,
  `fldUserId` INT NULL,
  `fldPincode` INT NULL,
  `fldState` VARCHAR(45) NULL,
  `fldCity` VARCHAR(45) NULL,
  `fldArea` VARCHAR(45) NULL,
  `fldBuilding` VARCHAR(45) NULL,
  `fldRecieverName` VARCHAR(45) NULL,
  `fldPhoneNumber` INT NULL,
  PRIMARY KEY (`fldOrder_Id`),
  INDEX `userid_idx` (`fldUserId` ASC) VISIBLE,
  CONSTRAINT `userid`
    FOREIGN KEY (`fldUserId`)
    REFERENCES `mydb`.`tblUser` (`flduser_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tblOrderList`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tblOrderList` (
  `fldOrderList_Id` INT NOT NULL,
  `fldOrderId` INT NULL,
  `fldQuantity` INT NULL,
  `fldProductName` VARCHAR(45) NULL,
  `fldPrice` DECIMAL(2) NULL,
  `fldTax` VARCHAR(45) NULL,
  `fldDescription` VARCHAR(200) NULL,
  `fldThumbnail` VARCHAR(45) NULL,
  `fldBrand` VARCHAR(45) NULL,
  PRIMARY KEY (`fldOrderList_Id`),
  INDEX `orderId_idx` (`fldOrderId` ASC) VISIBLE,
  CONSTRAINT `orderId`
    FOREIGN KEY (`fldOrderId`)
    REFERENCES `mydb`.`tblOrder` (`fldOrder_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tblCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tblCategory` (
  `fldcategory_Id` INT NOT NULL,
  `fldCreatedBy` INT NULL,
  `fldCategoryName` VARCHAR(45) NULL,
  `fldCreatedOn` DATETIME NULL,
  `fldUpdatedOn` DATETIME NULL,
  `fldUpdatedby` INT NULL,
  `fldDeletedOn` DATETIME NULL,
  `fldDeletedBy` INT NULL,
  `fldActive` INT NULL,
  PRIMARY KEY (`fldcategory_Id`),
  INDEX `createdBy_idx` (`fldCreatedBy` ASC) VISIBLE,
  INDEX `updatedBy_idx` (`fldUpdatedby` ASC) VISIBLE,
  INDEX `deletedBy_idx` (`fldDeletedBy` ASC) VISIBLE,
  UNIQUE INDEX `fldcategory_Id_UNIQUE` (`fldcategory_Id` ASC) VISIBLE,
  CONSTRAINT `createdBy`
    FOREIGN KEY (`fldCreatedBy`)
    REFERENCES `mydb`.`tblUser` (`flduser_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `updatedBy`
    FOREIGN KEY (`fldUpdatedby`)
    REFERENCES `mydb`.`tblUser` (`flduser_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `deletedBy`
    FOREIGN KEY (`fldDeletedBy`)
    REFERENCES `mydb`.`tblUser` (`flduser_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tblSubCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tblSubCategory` (
  `fldSubCategory_Id` INT NOT NULL,
  `fldCategoryId` INT NULL,
  `fldSubCategoryName` VARCHAR(45) NULL,
  `fldCreatedBy` INT NULL,
  `fldCreatedOn` DATETIME NULL,
  `fldUpdatedBy` INT NULL,
  `fldUpdatedOn` DATETIME NULL,
  `fldDeletedBy` INT NULL,
  `fldDeletedOn` DATETIME NULL,
  `fldActive` INT NULL,
  PRIMARY KEY (`fldSubCategory_Id`),
  INDEX `categoryId_idx` (`fldCategoryId` ASC) VISIBLE,
  INDEX `createdby_idx` (`fldCreatedBy` ASC) VISIBLE,
  CONSTRAINT `categoryId`
    FOREIGN KEY (`fldCategoryId`)
    REFERENCES `mydb`.`tblCategory` (`fldcategory_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `createdby`
    FOREIGN KEY (`fldCreatedBy`)
    REFERENCES `mydb`.`tblUser` (`flduser_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tblProduct`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tblProduct` (
  `fldProduct_Id` INT NOT NULL,
  `fldSubCategoryid` INT NULL,
  `fldProductName` VARCHAR(45) NULL,
  `fldBrand` VARCHAR(45) NULL,
  `fldDescription` VARCHAR(200) NULL,
  `fldPrice` DECIMAL(2) NULL,
  `fldTax` DECIMAL(2) NULL,
  `fldThumbnail` VARCHAR(100) NULL,
  `fldCreatedBy` INT NULL,
  `fldCreatedOn` DATETIME NULL,
  `fldUpdatedBy` INT NULL,
  `fldUpdatedOn` DATETIME NULL,
  `fldDeletedBy` INT NULL,
  `fldDeletedOn` DATETIME NULL,
  `fldActive` INT NULL,
  PRIMARY KEY (`fldProduct_Id`),
  INDEX `subcategoryId_idx` (`fldSubCategoryid` ASC) VISIBLE,
  INDEX `createdBy_idx` (`fldCreatedBy` ASC) VISIBLE,
  CONSTRAINT `subcategoryId`
    FOREIGN KEY (`fldSubCategoryid`)
    REFERENCES `mydb`.`tblSubCategory` (`fldSubCategory_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `createdBy`
    FOREIGN KEY (`fldCreatedBy`)
    REFERENCES `mydb`.`tblUser` (`flduser_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tblCart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tblCart` (
  `fldCart_Id` INT NOT NULL,
  `fldUserId` INT NULL,
  `fldProductId` INT NULL,
  `fldQuantity` INT NULL,
  `fldCreatedOn` DATETIME NULL,
  `fldUpdatedOn` DATETIME NULL,
  PRIMARY KEY (`fldCart_Id`),
  INDEX `userid_idx` (`fldUserId` ASC) VISIBLE,
  INDEX `fldProductId_idx` (`fldProductId` ASC) VISIBLE,
  CONSTRAINT `userid`
    FOREIGN KEY (`fldUserId`)
    REFERENCES `mydb`.`tblUser` (`flduser_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fldProductId`
    FOREIGN KEY (`fldProductId`)
    REFERENCES `mydb`.`tblProduct` (`fldProduct_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tblProductImages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tblProductImages` (
  `fldImage_Id` INT NOT NULL,
  `fldProductId` INT NULL,
  `fldImageAddress` VARCHAR(100) NULL,
  `fldCreatedBy` INT NULL,
  PRIMARY KEY (`fldImage_Id`),
  INDEX `productId_idx` (`fldProductId` ASC) VISIBLE,
  CONSTRAINT `productId`
    FOREIGN KEY (`fldProductId`)
    REFERENCES `mydb`.`tblProduct` (`fldProduct_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
